version: '3.7'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
